Repository Koniverse/SubWallet-React-UI, pull requests merged in 2023-01, with the labels that each got.

#31 Update icon
  components/config-provider/SizeContext.tsx
  components/icon/index.tsx
  components/icon/stories/icon.stories.tsx
  package.json
Labels: codeball:needs-review

#53 [Issue-16] Update component tags
  components/_util/colors.ts
  components/tag/index.tsx
  components/tag/stories/tag.stories.tsx
  components/tag/style/index.tsx
Labels: codeball:needs-careful-review

#30 [Issue-26] Update Image
  components/image/index.tsx
  components/image/stories/image.stories.tsx
  components/image/style/index.tsx
Labels: codeball:needs-careful-review

#52 Update button, icon, squircle
  .storybook/preview.tsx
  components/_util/colors.ts
  components/button/button.tsx
  components/button/stories/button.stories.tsx
  components/button/style/index.tsx
  components/config-provider/SizeContext.tsx
  components/icon/index.tsx
  components/squircle/index.tsx
  components/squircle/style/index.tsx
  components/theme/interface/maps/colors.ts
  components/theme/themes/dark/colors.ts
  components/theme/themes/default/colors.ts
  components/theme/themes/seed.ts
Labels: codeball:needs-careful-review

#54 Update link, switch components
  components/switch/stories/switch.stories.tsx
  components/switch/style/index.tsx
  components/theme/util/alias.ts
  components/tooltip/stories/tooltip.stories.tsx
  components/typography/Base/index.tsx
  components/typography/Link.tsx
  components/typography/Text.tsx
  components/typography/stories/link.stories.tsx
  components/typography/style/index.tsx
  components/typography/style/mixins.tsx
Labels: codeball:needs-careful-review

#55 [Issue-15] Component - Select (Modal)
  components/select-modal/PurePanel.tsx
  components/select-modal/SelectModal.tsx
  components/select-modal/hook/useInitSelectModal.ts
  components/select-modal/index.tsx
  components/select-modal/provider/index.tsx
  components/select-modal/stories/select-modal.stories.tsx
  components/select-modal/style/index.tsx
  components/theme/interface/components.ts
Labels: codeball:needs-careful-review

#56 [Issue-33] Component - Modal
  components/modal/PurePanel.tsx
  components/modal/stories/modal.stories.tsx
Labels: codeball:needs-review

#59 [Issue-1] Update Color Map and Color Preview
  .dumi/theme/common/Color/Palette.tsx
  components/theme/stories/colors.stories.tsx
  components/theme/themes/dark/index.ts
  components/theme/themes/default/index.ts
  components/theme/themes/seed.ts
Labels: codeball:needs-careful-review

#61 [Issue-5] Component - Number
  components/_util/number.ts
  components/number/index.tsx
  components/number/stories/number.stories.tsx
  components/number/style/index.ts
  components/theme/interface/components.ts
  package.json
Labels: codeball:needs-careful-review

#63 [Issue-6,9,10] Update file upload, icon components, switch storybook
  components/icon/index.tsx
  components/switch/stories/switch.stories.tsx
  components/theme/themes/dark/colors.ts
  components/upload/SingleFileDragger.tsx
  components/upload/Upload.tsx
  components/upload/index.tsx
  components/upload/interface.tsx
  components/upload/stories/singleFileDragger.stories.tsx
  components/upload/style/dragger.ts
Labels: codeball:needs-careful-review

#60 [Issue-36] Update Avatar
  .storybook/main.ts
  components/sw-avatar/index.tsx
  components/sw-avatar/stories/swavatar.stories.tsx
  components/sw-avatar/style/index.tsx
  components/theme/interface/components.ts
  package.json
Labels: codeball:needs-careful-review

#62 [Issue-37] Update Spin
  components/activity-indicator/index.tsx
  components/activity-indicator/stories/activity-indicator.stories.tsx
  components/activity-indicator/style/index.tsx
  components/theme/interface/components.ts
Labels: codeball:needs-careful-review

#65 [Issue-40] Update notification
  components/notification/NotificationProvider.tsx
  components/notification/PurePanel.tsx
  components/notification/interface.ts
  components/notification/stories/notification.stories.tsx
  components/notification/style/index.tsx
  components/notification/useNotification.tsx
  components/style/index.ts
  package.json
Labels: codeball:needs-careful-review

#66 [Issue-18] Update Address
  components/_util/address.ts
  components/typography/stories/address.stories.tsx
Labels: codeball:needs-review

#67 [Issue-34] Update QR
  components/qrcode/QrCodeIcon.png
  components/qrcode/index.tsx
  components/qrcode/stories/qrcode.stories.tsx
Labels: codeball:needs-review

#68 [Issue-6, 8, 39, 48] Update icon, form input, search components , form demo
  components/_util/statusUtils.ts
  components/form/stories/form.stories.tsx
  components/form/style/index.ts
  components/icon/index.tsx
  components/input/Input.tsx
  components/input/Password.tsx
  components/input/Search.tsx
  components/input/TextArea.tsx
  components/input/stories/input.stories.tsx
  components/input/stories/password.stories.tsx
  components/input/stories/search.stories.tsx
  components/input/stories/textarea.stories.tsx
  components/input/style/index.ts
  components/style/index.ts
  components/theme/themes/dark/colors.ts
  components/theme/themes/default/colors.ts
  components/theme/themes/seed.ts
  components/upload/style/dragger.ts
Labels: codeball:needs-careful-review

#64 [Issue-15] Component - Select (Modal) and [Issue-33] Component - Modal
  .storybook/preview.tsx
  components/_util/dom.ts
  components/modal/stories/modal.stories.tsx
  components/number/index.tsx
  components/select-modal/PurePanel.tsx
  components/select-modal/SelectModal.tsx
  components/select-modal/hook/useInitSelectModal.ts
  components/select-modal/provider/index.tsx
  components/select-modal/stories/select-modal.stories.tsx
  components/select-modal/style/index.tsx
  components/sw-modal/PurePanel.tsx
  components/sw-modal/SwConfirmDialog.tsx
  components/sw-modal/SwModal.tsx
  components/sw-modal/hook/useInitModal.ts
  components/sw-modal/index.tsx
  components/sw-modal/locale.tsx
  components/sw-modal/provider/index.tsx
  components/sw-modal/stories/sw-modal.stories.tsx
  components/sw-modal/style/index.tsx
  components/theme/interface/components.ts
  components/theme/interface/maps/style.ts
  components/theme/themes/dark/colors.ts
  components/theme/themes/shared/genColorMapToken.ts
  components/theme/themes/shared/genRadius.ts
Labels: codeball:needs-careful-review

#71 [Issue-49] Layout - Screen layout
  components/number/index.tsx
  components/number/style/index.ts
  components/select-modal/SelectModal.tsx
  components/select-modal/stories/select-modal.stories.tsx
  components/select-modal/style/index.tsx
  components/sw-header/SwHeader.tsx
  components/sw-header/config.tsx
  components/sw-header/index.tsx
  components/sw-header/stories/sw-header.stories.tsx
  components/sw-header/style/index.ts
  components/sw-screen-layout/SwScreenLayout.tsx
  components/sw-screen-layout/index.tsx
  components/sw-screen-layout/stories/sw-screen-layout.stories.tsx
  components/sw-screen-layout/style/index.ts
  components/sw-sub-header/SwSubHeader.tsx
  components/sw-sub-header/index.tsx
  components/sw-sub-header/stories/sw-sub-header.stories.tsx
  components/sw-sub-header/style/index.ts
  components/sw-tab-bar/SwTabBar.tsx
  components/sw-tab-bar/index.tsx
  components/sw-tab-bar/stories/sw-tab-bar.stories.tsx
  components/sw-tab-bar/style/index.ts
  components/theme/interface/components.ts
  components/theme/interface/seeds.ts
  components/theme/themes/seed.ts
Labels: codeball:needs-careful-review

#70 [Issue-27] Update pincode
  components/pincode/index.tsx
  components/pincode/stories/pincode.stories.tsx
  components/pincode/style/index.tsx
  components/style/index.ts
  components/theme/interface/components.ts
  package.json
  patches/react-pin-input+1.3.0.patch
Labels: codeball:needs-review

#72 Update Account Item
  components/logo/InnerLogo.tsx
  components/logo/index.tsx
  components/logo/stories/logo.stories.tsx
  components/sw-avatar/index.tsx
  components/sw-avatar/stories/swavatar.stories.tsx
  components/sw-avatar/style/index.tsx
  components/theme/interface/components.ts
  components/web3block/account-card/AccountCard.tsx
  components/web3block/account-card/AccountCardSelection.tsx
  components/web3block/account-card/AccountCardToggle.tsx
  components/web3block/account-card/index.tsx
  components/web3block/account-card/stories/selection.stories.tsx
  components/web3block/account-card/stories/toggle.stories.tsx
  components/web3block/account-card/style/index.tsx
  components/web3block/account-item/AccountItem.tsx
  components/web3block/account-item/AccountItemSelection.tsx
  components/web3block/account-item/index.ts
  components/web3block/account-item/stories/selection.stories.tsx
  components/web3block/account-item/stories/withLogo.stories.tsx
  components/web3block/account-item/style/index.tsx
Labels: codeball:needs-review

#83 [Issue-75] Update CrowdloanItem
  components/web3-block/crowdloan-item/index.tsx
  components/web3-block/crowdloan-item/stories/crowdloan-item.stories.tsx
  components/web3-block/crowdloan-item/style/index.tsx
Labels: codeball:approved

#82 [Issue-76] Update StakingItem
  components/theme/interface/components.ts
  components/web3-block/staking-item/index.tsx
  components/web3-block/staking-item/stories/staking-item.stories.tsx
  components/web3-block/staking-item/style/index.tsx
Labels: codeball:approved

#84 [Issue-80] Update DAppItem
  components/theme/interface/components.ts
  components/web3-block/dapp-item/index.tsx
  components/web3-block/dapp-item/stories/dapp-item.stories.tsx
  components/web3-block/dapp-item/style/index.ts
Labels: codeball:needs-review

#85 [Issue-81] Update StakingNetworkItem
  components/theme/interface/components.ts
  components/web3-block/staking-network-item/index.tsx
  components/web3-block/staking-network-item/stories/staking-network-item.stories.tsx
  components/web3-block/staking-network-item/style/index.ts
Labels: codeball:needs-review

#79 [Issue 43] Update SwList component
  components/input/Search.tsx
  components/sw-list/List.tsx
  components/sw-list/Section.tsx
  components/sw-list/index.ts
  components/sw-list/stories/data.ts
  components/sw-list/stories/flat-list.stories.tsx
  components/sw-list/style/index.ts
  components/theme/interface/components.ts
  package.json
Labels: codeball:needs-careful-review

#77 [Issue-50] Update web3-gallery components
  components/theme/interface/components.ts
  components/web3-gallery/base/index.tsx
  components/web3-gallery/base/style/index.ts
  components/web3-gallery/image-selection/index.tsx
  components/web3-gallery/image-selection/stories/image-selection.stories.tsx
  components/web3-gallery/image-selection/style/index.ts
  components/web3-gallery/nft-collection/index.tsx
  components/web3-gallery/nft-collection/stories/nft-collection.stories.tsx
  components/web3-gallery/nft-collection/style/index.ts
  components/web3-gallery/nft-item/index.tsx
  components/web3-gallery/nft-item/stories/nft-item.stories.tsx
  components/web3-gallery/nft-item/style/index.ts
Labels: codeball:needs-review

#78 [Issue-38] Component - QR Scanner
  components/button/style/index.ts
  components/select-modal/SelectModal.tsx
  components/select-modal/style/index.tsx
  components/sw-header/config.tsx
  components/sw-header/stories/sw-header.stories.tsx
  components/sw-qr-scanner/QrReader.tsx
  components/sw-qr-scanner/SwQrScanner.tsx
  components/sw-qr-scanner/hooks/useQrReader.ts
  components/sw-qr-scanner/index.tsx
  components/sw-qr-scanner/stories/sw-qr-scanner.stories.tsx
  components/sw-qr-scanner/style/index.ts
  components/sw-qr-scanner/types.ts
  components/sw-qr-scanner/utils.ts
  components/sw-screen-layout/stories/sw-screen-layout.stories.tsx
  components/theme/interface/components.ts
  package.json
Labels: codeball:needs-review

#92 [Issue 10,46] Fix some issues related to reviewer comments
  components/style/index.ts
  components/tooltip/stories/tooltip.stories.tsx
  components/upload/style/dragger.ts
Labels: codeball:needs-review

#87 [Issue-5] Component - Number
  components/number/index.tsx
Labels: codeball:needs-review

#89 [Issue-86] Update StakingValidatorItem
  components/theme/interface/components.ts
  components/web3-block/staking-validator-item/index.tsx
  components/web3-block/staking-validator-item/stories/staking-validator-item.stories.tsx
  components/web3-block/staking-validator-item/style/index.ts
Labels: codeball:needs-review

#93 [Issue-91] Update Setting Item
  components/background-icon/index.tsx
  components/background-icon/stories/background-icon.stories.tsx
  components/background-icon/style/index.ts
  components/theme/interface/components.ts
  components/web3-block/base/style/index.tsx
  components/web3-block/dapp-item/style/index.ts
  components/web3-block/setting-item/index.tsx
  components/web3-block/setting-item/stories/setting-item.stories.tsx
  components/web3-block/setting-item/style/index.ts
  components/web3-block/staking-network-item/style/index.ts
Labels: codeball:needs-review

#95 [Issue-51] Update style and logic for Web3BlockItem
  components/web3-block/account-card/index.tsx
  components/web3-block/account-card/stories/account-card.stories.tsx
  components/web3-block/account-card/style/index.tsx
  components/web3-block/account-item/index.tsx
  components/web3-block/account-item/stories/account-item.stories.tsx
  components/web3-block/account-item/style/index.tsx
  components/web3-block/balance-item/index.tsx
  components/web3-block/balance-item/stories/balance-item.stories.tsx
  components/web3-block/balance-item/style/index.tsx
  components/web3-block/base/index.tsx
  components/web3-block/crowdloan-item/index.tsx
  components/web3-block/dapp-item/index.tsx
  components/web3-block/network-item/index.tsx
  components/web3-block/network-item/stories/network-item.stories.tsx
  components/web3-block/setting-item/index.tsx
  components/web3-block/setting-item/stories/setting-item.stories.tsx
  components/web3-block/staking-item/index.tsx
  components/web3-block/staking-network-item/index.tsx
  components/web3-block/staking-network-item/stories/staking-network-item.stories.tsx
  components/web3-block/staking-validator-item/index.tsx
Labels: codeball:approved

#94 [Issue 4,8,39]
  components/button/button.tsx
  components/button/style/index.ts
  components/input/Input.tsx
  components/input/Password.tsx
  components/input/Search.tsx
  components/input/stories/input.stories.tsx
  components/input/style/index.ts
Labels: codeball:needs-careful-review

#97 [Issue-40] Update style for Notification
  components/notification/NotificationProvider.tsx
  components/notification/PurePanel.tsx
  components/notification/style/index.tsx
Labels: codeball:needs-careful-review

#98 [Issue-36] Update SwAvatar
  components/sw-avatar/index.tsx
  components/sw-avatar/stories/swavatar.stories.tsx
  package.json
Labels: codeball:approved

#99 [Issue-49] Layout - Screen layout
  components/sw-header/SwHeader.tsx
  components/sw-header/stories/sw-header.stories.tsx
  components/sw-header/style/index.ts
  components/sw-screen-layout/stories/header-content.tsx
  components/sw-screen-layout/stories/header-icons.tsx
  components/sw-screen-layout/stories/sw-screen-layout.stories.tsx
  components/sw-sub-header/SwSubHeader.tsx
  components/sw-sub-header/style/index.ts
  components/sw-tab-bar/stories/sw-tab-bar.stories.tsx
  components/sw-tab-bar/stories/tab-bar-items.ts
Labels: codeball:needs-review

#100 [Issue-38] Component - QR Scanner
  components/progress/style/index.tsx
  components/sw-qr-scanner/SwQrScanner.tsx
  components/sw-qr-scanner/style/index.ts
Labels: codeball:needs-review

#101 [Issue-33] Component - Modal
  components/select-modal/SelectModal.tsx
  components/select-modal/stories/select-modal.stories.tsx
  components/select-modal/style/index.tsx
  components/sw-modal/PurePanel.tsx
  components/sw-modal/SwConfirmDialog.tsx
  components/sw-modal/stories/sw-modal.stories.tsx
Labels: codeball:needs-review

#103 [Issue-6] Update BackgroundIcon
  components/theme/interface/components.ts
Labels: codeball:approved

#102 [Issue-35] Update Logo
  components/logo/index.tsx
  components/logo/stories/logo.stories.tsx
Labels: codeball:approved

#104 [Issue-51] Update BalanceItem, CrowdloanItem, NetworkItem
  components/web3-block/balance-item/index.tsx
  components/web3-block/crowdloan-item/index.tsx
  components/web3-block/network-item/index.tsx
Labels: codeball:approved

#107 [Issue-37] Update Activity Indicator
  components/activity-indicator/index.tsx
  components/activity-indicator/stories/activity-indicator.stories.tsx
Labels: codeball:needs-review

#105 [Issue-69] Fix some style bug
  components/image/index.tsx
  components/image/stories/image.stories.tsx
  components/qrcode/index.tsx
  components/qrcode/stories/qrcode.stories.tsx
  components/style/index.ts
  components/typography/stories/address.stories.tsx
Labels: codeball:needs-review

#106 [Issue-49] Layout - Screen layout
  components/sw-screen-layout/stories/header-content.tsx
Labels: codeball:approved

#108 [Issue 48] Update form demo
  components/form/FormItem/index.tsx
  components/form/stories/form.stories.tsx
  components/form/style/index.ts
  components/input/Input.tsx
  components/input/TextArea.tsx
  components/input/stories/input.stories.tsx
  components/input/stories/password.stories.tsx
  components/input/stories/search.stories.tsx
  components/input/stories/textarea.stories.tsx
  components/input/style/index.ts
  package.json
  scripts/check-commit.js
Labels: codeball:needs-careful-review

#109 [Issue-27] Update PinCode
  components/pincode/index.tsx
  components/pincode/stories/pincode.stories.tsx
  components/pincode/style/index.tsx
Labels: codeball:approved

#115 [Update-UI] Issues 15, 33, 38, 41, 42, 49
  components/_util/browser.ts
  components/notification/NotificationProvider.tsx
  components/select-modal/SelectModal.tsx
  components/select-modal/stories/select-modal.stories.tsx
  components/select-modal/style/index.tsx
  components/sw-header/config/index.tsx
  components/sw-modal/style/index.tsx
  components/sw-qr-scanner/SwQrScanner.tsx
  components/sw-qr-scanner/config/index.ts
  components/sw-qr-scanner/stories/sw-qr-scanner.stories.tsx
  components/sw-qr-scanner/style/index.ts
  components/sw-screen-layout/SwScreenLayout.tsx
  components/sw-screen-layout/stories/sw-screen-layout.stories.tsx
  components/sw-screen-layout/style/index.ts
  components/sw-sub-header/style/index.ts
  components/sw-tab-bar/style/index.ts
  components/theme/interface/alias.ts
  components/theme/util/alias.ts
Labels: codeball:needs-careful-review

#114 [Issue-81] Update StakingNetworkItem
  components/web3-block/staking-network-item/stories/staking-network-item.stories.tsx
  components/web3-block/staking-network-item/style/index.ts
Labels: codeball:approved

#113 [Issue-34] Update QR
  components/qrcode/index.tsx
  components/qrcode/stories/qrcode.stories.tsx
Labels: codeball:needs-review

#112 [Issue-74] Update BalanceItem
  components/web3-block/balance-item/style/index.tsx
Labels: codeball:approved

#116 [Issue-88] Update NetworkItem
  components/web3-block/network-item/index.tsx
  components/web3-block/network-item/stories/network-item.stories.tsx
  components/web3-block/network-item/style/index.ts
Labels: codeball:approved

#117 [Issue-80] Update DAppItem, SettingItem
  components/web3-block/dapp-item/stories/dapp-item.stories.tsx
  components/web3-block/setting-item/stories/setting-item.stories.tsx
Labels: codeball:needs-review

#119 [Issue 118] Fix import issue for @subwallet/react-ui
  components/activity-indicator/index.tsx
  components/form/__tests__/index.test.tsx
  components/form/hooks/useFormItemStatus.ts
  components/icon/index.tsx
  components/index.ts
  components/logo/index.tsx
  components/number/index.tsx
  components/squircle/index.tsx
  components/sw-tab-bar/stories/tab-bar-items.ts
  components/theme/themes/dark/index.ts
  components/theme/themes/default/index.ts
  components/theme/themes/logoMap.ts
  components/web3-gallery/image-selection/index.tsx
  components/web3-gallery/image-selection/stories/image-selection.stories.tsx
Labels: codeball:needs-careful-review
