Repository Koniverse/SubWallet-React-UI, pull requests merged in 2023-02, with the labels that each got.

#120 [Issue 118] Fix some issues cause package unable to build
  components/background-icon/index.tsx
  components/icon/index.tsx
  components/icon/stories/icon.stories.tsx
  components/index.ts
  components/input/Input.tsx
  components/input/TextArea.tsx
  components/sw-tab-bar/SwTabBar.tsx
Labels: codeball:needs-careful-review

#121 [Issue-38] Component - QR Scanner
  components/background-icon/index.tsx
  components/pagination/Pagination.tsx
  components/select-modal/SelectModal.tsx
  components/select-modal/stories/select-modal.stories.tsx
  components/select/index.tsx
  components/sw-header/SwHeader.tsx
  components/sw-qr-scanner/SwQrScanner.tsx
  components/sw-qr-scanner/stories/sw-qr-scanner.stories.tsx
  components/sw-screen-layout/SwScreenLayout.tsx
  components/sw-screen-layout/stories/sw-screen-layout.stories.tsx
  components/sw-sub-header/style/index.ts
  components/sw-tab-bar/style/index.ts
Labels: codeball:needs-careful-review

#122 [Issue-74] Fix icon color
  components/web3-block/balance-item/style/index.tsx
  components/web3-block/network-item/style/index.ts
  components/web3-block/setting-item/style/index.ts
  components/web3-block/staking-item/style/index.tsx
Labels: codeball:needs-review

#124 [Issue-43] Update SwList
  components/style/index.ts
  components/sw-list/stories/flat-list.stories.tsx
  components/sw-list/style/index.ts
Labels: codeball:needs-review

#125 [Issue-75] Update CrowdloanItem
  components/index.ts
  components/web3-block/crowdloan-item/index.tsx
Labels: codeball:needs-review

#126 [Issue-43] Fix bug document is not defined
  components/style/index.ts
Labels: codeball:approved

#129 [Update-UI] Issues 15, 38, 49
  components/_util/colors.ts
  components/button/button.tsx
  components/button/style/index.ts
  components/select-modal/SelectModal.tsx
  components/select-modal/stories/select-modal.stories.tsx
  components/select-modal/style/index.tsx
  components/sw-header/SwHeader.tsx
  components/sw-header/configs/index.tsx
  components/sw-header/icons/MenuBar.tsx
  components/sw-header/index.tsx
  components/sw-header/stories/sw-header.stories.tsx
  components/sw-header/style/index.ts
  components/sw-list/Section.tsx
  components/sw-modal/SwModal.tsx
  components/sw-modal/index.tsx
  components/sw-qr-scanner/SwQrScanner.tsx
  components/sw-qr-scanner/configs/index.ts
  components/sw-screen-layout/SwScreenLayout.tsx
  components/sw-screen-layout/stories/header-content.tsx
  components/sw-screen-layout/stories/header-icons.tsx
  components/sw-screen-layout/stories/sw-screen-layout.stories.tsx
  components/sw-screen-layout/style/index.ts
  components/sw-sub-header/SwSubHeader.tsx
  components/sw-sub-header/index.tsx
  components/sw-sub-header/stories/sw-sub-header.stories.tsx
  components/sw-sub-header/style/index.ts
  components/web3-block/base/style/index.tsx
Labels: codeball:needs-careful-review

#132 [Issue-33] Component - Modal
  components/button/style/index.ts
  components/select-modal/SelectModal.tsx
  components/sw-header/SwHeader.tsx
  components/sw-modal/SwModal.tsx
  components/sw-modal/index.tsx
  components/sw-modal/style/index.tsx
  components/sw-sub-header/SwSubHeader.tsx
Labels: codeball:needs-review

#135 [Issue-133] Component - Page Icon
  components/page-icon/PageIcon.tsx
  components/page-icon/index.tsx
  components/page-icon/stories/page-icon.stories.tsx
  components/page-icon/style/index.ts
  components/theme/interface/components.ts
Labels: codeball:needs-review

#136 [Issue-134] Component - Field
  components/field/Field.tsx
  components/field/index.tsx
  components/field/stories/field.stories.tsx
  components/field/style/index.tsx
  components/index.ts
  components/theme/interface/components.ts
Labels: codeball:needs-review

#137 Issue 26
  components/_util/constant.ts
  components/activity-indicator/index.tsx
  components/icon/index.tsx
  components/image/index.tsx
  components/image/stories/image.stories.tsx
  components/image/style/index.ts
  components/input/Input.tsx
  components/input/TextArea.tsx
  components/input/stories/search.stories.tsx
  components/input/style/index.ts
  components/notification/NotificationProvider.tsx
  components/notification/useNotification.tsx
  components/number/index.tsx
  components/select-modal/SelectModal.tsx
  components/sw-avatar/index.tsx
  components/sw-avatar/stories/swavatar.stories.tsx
  components/sw-avatar/style/index.tsx
  components/sw-modal/SwConfirmDialog.tsx
  components/sw-modal/style/index.tsx
  components/web3-block/account-card/index.tsx
  components/web3-block/account-item/index.tsx
  components/web3-block/balance-item/index.tsx
  components/web3-block/base/style/index.tsx
  components/web3-block/crowdloan-item/index.tsx
  components/web3-block/staking-item/index.tsx
  components/web3-block/staking-network-item/index.tsx
  components/web3-block/staking-validator-item/index.tsx
Labels: codeball:needs-careful-review
